import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db';
import AutoPrompt from '@/models/AutoPrompt';
import Article from '@/models/Article';
import { generateArticle } from '@/lib/ai';

// Vercel Cron timing: 4:45 AM IST (23:15 UTC)
// This endpoint must be secured
export async function GET(request: Request) {
    try {
        await dbConnect();

        const authHeader = request.headers.get('authorization');
        if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // 1. Fetch Active Prompts
        const activePrompts = await AutoPrompt.find({ isActive: true });

        if (activePrompts.length === 0) {
            return NextResponse.json({ message: 'No active prompts found.' });
        }

        const results = [];

        // 2. Process each prompt
        for (const prompt of activePrompts) {
            try {
                // Generate Content
                const rawContent = await generateArticle(prompt.promptTemplate);

                // Parse the AI response (Simple parsing assumption for now)
                // We assume the AI follows the requested format.
                // In a real app, we'd use regex to extract Title/Body better.

                // Quick cleanup to extract title (First line # Title)
                const lines = rawContent.split('\n');
                let title = 'Auto Generated Article';
                let content = rawContent;

                const titleMatch = rawContent.match(/^#\s*(.+)$/m);
                if (titleMatch) {
                    title = titleMatch[1].trim();
                    content = rawContent.replace(/^#\s*.+$/m, '').trim(); // Remove title from body
                }

                // Create Slug
                const slug = title
                    .toLowerCase()
                    .replace(/[^a-z0-9]+/g, '-')
                    .replace(/(^-|-$)+/g, '') + '-' + Date.now(); // Ensure uniqueness

                // Create Article
                const newArticle = await Article.create({
                    title,
                    slug,
                    excerpt: content.substring(0, 150) + '...', // Simple excerpt
                    content, // Store Markdown directly
                    category: prompt.category,
                    author: 'T20 Masala Desk',
                    status: 'published',
                    isAutoGenerated: true,
                    autoPromptId: prompt._id,
                    publishedAt: new Date(),
                });

                // Update Prompt Run Time
                prompt.lastRunAt = new Date();
                await prompt.save();

                results.push({ prompt: prompt.title, articleId: newArticle._id, status: 'success' });

            } catch (err: any) {
                console.error(`Failed to run prompt ${prompt.title}:`, err);
                results.push({ prompt: prompt.title, error: err.message, status: 'failed' });
            }
        }

        return NextResponse.json({ success: true, results });

    } catch (error: any) {
        return NextResponse.json({ error: 'Internal Server Error', details: error.message }, { status: 500 });
    }
}
